# Generated by Django 5.2.5 on 2025-08-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_contact_alter_services_decription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
