# Generated by Django 5.2.5 on 2025-08-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_delete_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
